INSERT INTO companies (id,name) VALUES (1,'AEP');
INSERT INTO companies (id,name) VALUES (2,'CITY UTILITIES');
INSERT INTO companies (id,name) VALUES (3,'NIPSCO');
INSERT INTO companies (id,name) VALUES (4,'AEP2');
INSERT INTO companies (id,name) VALUES (5,'DELETEABLE');
INSERT INTO companies (id,name) VALUES (6,'UPDATABLE');
INSERT INTO bills (billing_month,billing_year,company_id,city,amount) VALUES (11,2023,1,'Lucknow',50);
INSERT INTO bills (billing_month,billing_year,company_id,city,amount) VALUES (11,2022,1,'Lucknow',65);
INSERT INTO bills (billing_month,billing_year,company_id,city,amount) VALUES (12,2023,1,'Lucknow',72);
INSERT INTO bills (billing_month,billing_year,company_id,city,amount) VALUES (12,2022,1,'Lucknow',81);
INSERT INTO bills (billing_month,billing_year,company_id,city,amount) VALUES ( 1,2024,1,'Lucknow',90);
INSERT INTO bills (billing_month,billing_year,company_id,city,amount) VALUES ( 1,2023,1,'Lucknow',105);
INSERT INTO bills (billing_month,billing_year,company_id,city,amount) VALUES ( 1,2023,3,'Lucknow',88);
INSERT INTO bills (billing_month,billing_year,company_id,city,amount) VALUES ( 2,2024,1,'Lucknow',109);
INSERT INTO bills (billing_month,billing_year,company_id,city,amount) VALUES ( 2,2023,1,'Lucknow',123);
INSERT INTO bills (billing_month,billing_year,company_id,city,amount) VALUES ( 3,2024,1,'Lucknow',135);
INSERT INTO bills (billing_month,billing_year,company_id,city,amount) VALUES ( 3,2023,1,'Lucknow',145);
INSERT INTO bills (billing_month,billing_year,company_id,city,amount) VALUES ( 7,2124,4,'Lucknow',1000000);
INSERT INTO bills (billing_month,billing_year,company_id,city,amount) VALUES ( 5,2022,4,'Lucknow',90);
INSERT INTO bills (billing_month,billing_year,company_id,city,amount) VALUES ( 5,2022,6,'Lucknow',90);
